## 使用 TF1.x 默认了开启 Eager execution

In [1]:
import tensorflow as tf

tf = tf.compat.v1

In [2]:
data_dict = {'key1': 'value1', 'key2': 'value2'}
target_values = ','.join(str(dict_val) for dict_val in data_dict.values())
target_values

'value1,value2'

In [3]:
tensor = tf.convert_to_tensor(target_values)
tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'value1,value2'>

In [4]:
dict_value = {"key1": "value1","key2": "value2"}
dict_string = str(dict_value)
tensor_data = tf.constant(dict_string)
tensor_data

<tf.Tensor: shape=(), dtype=string, numpy=b"{'key1': 'value1', 'key2': 'value2'}">

In [13]:
# 如果关闭了 Eager execution，则不能使用 numpy() 方法获取数据

In [5]:
# mock message 到了 tensor 的状态，现在开始解析
invalid_dict = tensor_data.numpy().decode('utf-8')
invalid_dict

"{'key1': 'value1', 'key2': 'value2'}"

In [6]:
vaid_dict = invalid_dict.replace("'", '"')
vaid_dict

'{"key1": "value1", "key2": "value2"}'

In [7]:
# tensor 转为 dict 修改内容，然后再恢复成 value tensor

In [8]:
import json

dict_msg = json.loads(vaid_dict).values()
dict_msg

dict_values(['value1', 'value2'])

In [9]:
target_val = ','.join(str(temp) for temp in dict_msg)
target_val

'value1,value2'

In [10]:
# 修改内容
target_val = target_val + ',value3'
target_val

'value1,value2,value3'

In [11]:
# 重新转为 tensor
tf.convert_to_tensor(target_val)

<tf.Tensor: shape=(), dtype=string, numpy=b'value1,value2,value3'>